version: "3"

services:
  phpmyadmin:
    build:
      context: .
    container_name: phpmyadmin
    restart: "always"    
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - 8078:80
    networks:
      - network-lan
    volumes:
      - /DOCKER/volume/phpmyadmin/sessions
      - /DOCKER/volume/phpmyadmin/config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
     
networks:
  network-lan:
    external: true
